<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Throwable;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Tymon\JWTAuth\Exceptions\TokenInvalidException;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        Log::error($e);
        if ($e instanceof ModelNotFoundException && request()->ajax()) {
            return response()->json([
                'status' => 404,
                'mensagem' => 'Objeto requisitado não existe.'
            ], 404);
        }
        if ($e instanceof NotFoundHttpException && request()->ajax()) {
            return response()->json([
                'status' => 404,
                'mensagem' => 'a URI requisitada não existe, verifique a url e tente novamente.'
            ], 404);
        }
        if ($e instanceof AuthorizationException) {
            return response()->json([
                'status' => 403,
                'mensagem' => 'Sem Permissoes para executar esta ação.'
            ], 403);
        }
        if ($e instanceof TokenInvalidException) {
            return response()->json([
                'status' => 403,
                'mensagem' => 'Token Inválido'
            ], 403);
        }
        if ($e instanceof TokenExpiredException) {
            return response()->json([
                'status' => 403,
                'mensagem' => 'Token Expirado'
            ], 403);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
